openapi: 3.0.3
info:
  title: Marriage Allowance
  description: "This API provides resources related to [Marriage Allowance](https://www.gov.uk/marriage-allowance).\n\nMarriage Allowance lets the lower earner of a couple transfer some of their Personal Allowance to their husband, wife or civil partner. If they are eligible this will then lower their tax bill.\n\nIn particular, this API can\n\n* Retrieve an individual’s Marriage Allowance status\n* Check their partner’s eligibility to be a recipient of Marriage Allowance (useful if the individual is considering applying for Marriage Allowance)\nOn 28 February 2020 version 1.0 will be switched off.\n\nIf you are deploying after 28 February 2020, you should build based on version 2.0.\n\nIf you are deploying before 28 February 2020, you can continue building based on version 1.0 until that date. You must switch to version 2.0 on 28 February 2020.\n\nVersion 2.0 will be available from 23 October 2019 within the Sandbox and Production environment.\nThe endpoint in this API is [user-restricted](https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints). \nYour users must grant authority for your software to access it by signing in to their HMRC online account.\n\nThe API supports individual and agent users. Note that:\n- Individual users can only access their own information.\n- Agent users can only access their own clients’ data.\n\nThe following options are supported for agents:\n\n**Option 1: Agent services account**\n\nIf the agent uses an [agent services account](https://www.gov.uk/government/collections/hmrc-online-services-for-agents#agent-services-account),\nthey can access their [existing 64-8 clients](https://www.gov.uk/guidance/client-authorisation-an-overview)\nwho they have [linked to their agent services account](https://www.gov.uk/guidance/link-clients-to-your-agent-services-account#link-existing-clients)\n(restricted to 2 years’ history)\n\n**Option 2: HMRC online services for agents account**\n\nIf the agent uses an [HMRC online services for agents account](https://www.gov.uk/government/collections/hmrc-online-services-for-agents#hmrc-online-services-for-agents-account)\nwhich is enrolled for [Self Assessment for Agents](https://www.gov.uk/guidance/self-assessment-for-agents-online-service),\nthey will be able to access their [existing 64-8 clients](https://www.gov.uk/guidance/client-authorisation-an-overview)\n(restricted to 2 years’ history).\nWhen an API changes in a way that is backwards-incompatible, we increase the version number of the API. \nSee our [reference guide](/api-documentation/docs/reference-guide#versioning) for more on\nversioning.\nWe use standard HTTP status codes to show whether an API request succeeded or not. They are usually in the range:\n* 200 to 299 if it succeeded, including code 202 if it was accepted by an API that needs to wait for further action\n* 400 to 499 if it failed because of a client error by your application\n* 500 to 599 if it failed because of an error on our server\n\nErrors specific to each API are shown in the Endpoints section, under Response. \nSee our [reference guide](/api-documentation/docs/reference-guide#errors) for more on errors.\nYou can use the sandbox environment to [test this API](https://developer.service.hmrc.gov.uk/api-documentation/docs/testing).\n\nIt supports [stateful behaviour](https://developer.service.hmrc.gov.uk/api-documentation/docs/testing/stateful-behaviour). You can set up test data for this API using the [Marriage Allowance Test Support API](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/marriage-allowance-des-stub)."
  contact: {}
  version: '1.0'
servers:
  - url: https://api.service.hmrc.gov.uk/
    description: Production
    variables: {}
paths:
  /marriage-allowance/sa/{utr}/status:
    get:
      tags:
        - marriage-allowance
      summary: Get Marriage Allowance status
      description: >
        @*
         * Copyright 2022 HM Revenue & Customs
         *
         *@

        <p>This resource determines whether an individual taxpayer has Marriage Allowance for the given tax year. If they have Marriage Allowance it will return their role in the relationship (either 'Transferor' or 'Recipient').</p>
      operationId: GetMarriageAllowancestatus
      parameters:
        - name: utr
          in: path
          description: The 10 digit self-assessment UTR for the individual.
          required: true
          style: simple
          schema:
            type: string
            example: '2234567890'
        - name: taxYear
          in: query
          description: The tax year for which the Marriage Allowance status is being retrieved, in the format YYYY-YY.
          required: true
          style: form
          explode: true
          schema:
            type: string
            example: 2014-15
      responses:
        '200':
          description: 'OK'
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/MarriageAllowanceSaStatusresponse'
                  - example:
                      status: Recipient
                      deceased: false
              examples:
                example-1:
                  value:
                    status: Recipient
                    deceased: false
        '400':
          description: 'Bad Request'
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/errorResponse'
                  - example:
                      code: SA_UTR_INVALID
              examples:
                invalidUtr:
                  description: Invalid UTR
                  value:
                    code: SA_UTR_INVALID
                invalidTaxYear:
                  description: Invalid tax year
                  value:
                    code: TAX_YEAR_INVALID
                missingTaxYear:
                  description: Missing tax year
                  value:
                    code: TAX_YEAR_INVALID
        '401':
          description: 'Unauthorised'
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/errorResponse'
                  - example:
                      code: UNAUTHORIZED
              examples:
                unauthorisedUser:
                  description: User not authorised
                  value:
                    code: UNAUTHORIZED
        '404':
          description: 'Not Found'
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/errorResponse'
                  - example:
                      code: NOT_FOUND
              examples:
                unmatchedRecipient:
                  description: Unmatched recipient
                  value:
                    code: NOT_FOUND
      deprecated: false
      security:
        - User-Restricted:
            - read:marriage-allowance
  /marriage-allowance/sa/{utr}/eligibility:
    get:
      tags:
        - marriage-allowance
      summary: Check Marriage Allowance eligibility
      description: >
        @*
         * Copyright 2022 HM Revenue & Customs
         *
         *@

        <p> This resource checks whether an individual taxpayer's partner is eligible to become a recipient of Marriage
            Allowance for the given tax year.</p>

        <p>This resource should only be used when the individual is the lower earner and is considering becoming a
            transferor of Marriage Allowance. It should only be used to to check the eligibility of their own partner.</p>
      operationId: CheckMarriageAllowanceeligibility
      parameters:
        - name: utr
          in: path
          description: The 10 digit self-assessment UTR for the individual.
          required: true
          style: simple
          schema:
            type: string
            example: '2234567890'
        - name: nino
          in: query
          description: Partner’s (potential recipient’s) National Insurance number
          required: true
          style: form
          explode: true
          schema:
            type: string
            example: AA000003D
        - name: firstname
          in: query
          description: Partner’s (potential recipient’s) first name
          required: true
          style: form
          explode: true
          schema:
            type: string
            example: John
        - name: surname
          in: query
          description: Partner’s (potential recipient’s) surname
          required: true
          style: form
          explode: true
          schema:
            type: string
            example: Smith
        - name: dateOfBirth
          in: query
          description: Partner’s (potential recipient’s) date of birth in YYYY-MM-DD format
          required: true
          style: form
          explode: true
          schema:
            type: string
            example: 1981-01-31
        - name: taxYear
          in: query
          description: The tax year for which the Marriage Allowance eligibility is being retrieved, in the format YYYY-YY.
          required: true
          style: form
          explode: true
          schema:
            type: string
            example: 2014-15
      responses:
        '200':
          description: 'OK'
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/MarriageAllowanceSaEligibilityresponse'
                  - example:
                      eligible: true
              examples:
                example-1:
                  value:
                    eligible: true
        '400':
          description: 'Bad Request'
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/errorResponse'
                  - example:
                      code: SA_UTR_INVALID
              examples:
                invalidUtr:
                  description: Invalid UTR
                  value:
                    code: SA_UTR_INVALID
                invalidNino:
                  description: Invalid NINO
                  value:
                    code: NINO_INVALID
                missingNino:
                  description: Missing NINO
                  value:
                    code: NINO_INVALID
                invalidDateOfBirth:
                  description: Invalid date of birth
                  value:
                    code: DOB_INVALID
                missingDateOfBirth:
                  description: Missing date of birth
                  value:
                    code: DOB_INVALID
                invalidTaxYear:
                  description: Invalid tax year
                  value:
                    code: TAX_YEAR_INVALID
                missingTaxYear:
                  description: Missing tax year
                  value:
                    code: TAX_YEAR_INVALID
                missingFirstName:
                  description: Missing first name
                  value:
                    code: BAD_REQUEST
                missingSurname:
                  description: Missing surname
                  value:
                    code: BAD_REQUEST
        '401':
          description: 'Unauthorised'
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/errorResponse'
                  - example:
                      code: UNAUTHORIZED
              examples:
                unauthorisedUser:
                  description: User not authorised
                  value:
                    code: UNAUTHORIZED
        '404':
          description: 'Not Found'
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/errorResponse'
                  - example:
                      code: NOT_FOUND
              examples:
                unmatchedRecipient:
                  description: Unmatched recipient
                  value:
                    code: NOT_FOUND
      deprecated: false
      security:
        - User-Restricted:
            - read:marriage-allowance
components:
  securitySchemes:
    User-Restricted:
      type:  oauth2
      description: HMRC supports OAuth 2.0 for authenticating User-restricted API requests
      flows:
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes:
            read:marriage-allowance: Access Marriage Allowance
  schemas:
    errorResponse:
      title: errorResponse
      required:
        - code
      type: object
      properties:
        code:
          type: string
    MarriageAllowanceSaEligibilityresponse:
      title: MarriageAllowanceSaEligibilityresponse
      required:
        - eligible
      type: object
      properties:
        eligible:
          type: boolean
          description: Whether the taxpayer's partner is eligible to become a recipient of Marriage Allowance.
      description: Marriage Allowance eligibility
    MarriageAllowanceSaStatusresponse:
      title: MarriageAllowanceSaStatusresponse
      required:
        - status
        - deceased
      type: object
      properties:
        status:
          oneOf:
            - $ref: '#/components/schemas/Status'
            - $ref: '#/components/schemas/Status1'
            - $ref: '#/components/schemas/Status2'
          description: The role of the taxpayer as recipient or transferor.
        deceased:
          type: boolean
          description: Whether the taxpayer is deceased or not.
      description: Marriage Allowance status
    Status:
      title: Status
      enum:
        - Transferor
      type: string
      description: The taxpayer has transferred personal allowance in the given tax year
    Status1:
      title: Status1
      enum:
        - Recipient
      type: string
      description: The taxpayer has received personal allowance in the given tax year
    Status2:
      title: Status2
      enum:
        - None
      type: string
      description: The taxpayer has not transferred or received personal allowance in the given tax year
tags:
  - name: marriage-allowance
    description: ''